sclang/lexer: define all newline literals to be '\n', not the platform default (#7545)
* sclang/lexer: define all newline literals to be '\n', not the platform default

Previously there was a nasty bug where strings with newlines in them depended on the author's os and editor when written in the class library.

This led to this bug that existed on windows when the class was written by a user.
```
A {
  ^str { ^"meow
woof"}
}

A.str != "meow
woof";
```
This is because on windows the newline character is actually two, \r\n, but on unix, and when something is checked into a git repo, and in the sc ide's runtime evaluation mode, the newline character is '\n'.

As well as converting all \r\n into \n, this pr also converts all \r into \n, this is because ancient macs (before 2001) used to use \r as thier newline character and we still have some code that does that.

Further, we redefine that the only whitespace character the ascii literal `$ ` can represent is the ascii space ' '. The error message for this looks as follows:
```
Lexing Error:
──────────────────────────────────────────────────────────────────────────────────
Error: /home/jordan/.repo/SuperCollider/SCClassLibrary/SCDoc/SCDoc.sc:1:1
──────────────────────────────────────────────────────────────────────────────────
    1 │ $
      ┆ ^ replace with $\n.
    2 │
```

This is done because previously the lexer would turn this runtime code `$` into `$ `, as it would always insert a space at the end of the evaluated code (else it got stuck in an inifitine loop).

Fixes #7520
Fixes #7523
Fixes #7509